### PR TITLE
Use only cxx14 features in clustering extension.

### LINKED ISSUE #31: conda-forges osx build does not work for SDK issues
Failing build: https://dev.azure.com/marscher/sktime/_build/results?buildId=36&view=logs&j=0a2947bc-4ed7-5966-e5d8-17037b1704c1

Maybe using c++14 can cure it: https://github.com/pybind/python_example/issues/44

### PR DESCRIPTION
**Pull request by marscher**
Also disable circle ci and update pybind11 to 2.4.2

fixes #31

### CODE REVIEW

File: sktime/clustering/include/metric.h [hunk 1]
```diff
@@ -16,17 +16,17 @@ namespace py = pybind11;
...
-        if constexpr (std::is_same_v<T, float>) {
-            return compute_f(xs, ys, dim);
-        } else {
-            return compute_d(xs, ys, dim);
-        }
+        return compute_d(xs, ys, dim);
     }
+	float compute(const float* xs, const float* ys, std::size_t dim) const {
+		return compute_f(xs, ys, dim);
+	}
```
Comment (clonker) [inline sktime/clustering/include/metric.h]: this isnt actually doing the same thing as far as i can tell, the way to work around `if constexpr` would be with `std::enable_if`

**Comment by marscher** [comment]
Thanks for the review. Please go ahead and change it accordingly

Am 14. Oktober 2019 19:11:59 MESZ schrieb Moritz Hoffmann <notifications@github.com>:
>clonker commented on this pull request.
>
>Apart from the if constexpr thing looks good to me! I can make the
>change as well if you want
>
>> -        if constexpr (std::is_same_v<T, float>) {
>-            return compute_f(xs, ys, dim);
>-        } else {
>-            return compute_d(xs, ys, dim);
>-        }
>+        return compute_d(xs, ys, dim);
>     }
>+	float compute(const float* xs, const float* ys, std::size_t dim)
>const {
>+		return compute_f(xs, ys, dim);
>+	}
>
>this isnt actually doing the same thing as far as i can tell, the way
>to work around `if constexpr` would be with `std::enable_if`
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scikit-time/scikit-time/pull/32#pullrequestreview-301434344

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by clonker** [comment]
Not sure why this failed, says 
```##[error]Error: Failed find: EPERM: operation not permitted, scandir '/Users/vsts/Library/Application Support/AddressBook'```
in the test result publishing step
